name: update-deployment
on:
  workflow_dispatch:
    inputs:
      filePath:
        description: 'Path to YAML file to update'
        required: true
      propertyPath:
        description: 'Property path to update'
        required: true
      propertyValue:
        description: 'Property value to update'
        required: true

jobs:
  update-deployment:
    name: Update deployment YAML file
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Update deployment YAML
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: ${{ github.event.inputs.filePath }}
          propertyPath: ${{ github.event.inputs.propertyPath }}
          value: ${{ github.event.inputs.propertyValue }}
          message: 'update ${{ github.event.inputs.filePath }} to ${{ github.event.inputs.propertyValue }}' 
          updateFile: true